apiVersion: v1
kind: AdminCluster
# (Required) Absolute path to a GKE bundle on disk
bundlePath: /var/lib/gke/bundles/gke-onprem-vsphere-1.5.0-gke.27-full.tgz
# (Required) vCenter configuration
vCenter:
  address: vcva.packet.local
  datacenter: Packet
  cluster: Packet-1
  resourcePool: Packet-1/Resources
  datastore: datastore1
  # Provide the path to vCenter CA certificate pub key for SSL verification
  caCertPath: ../vspherecert.pem
  # The credentials and address to connect to vCenter
  credentials:
    username: Administrator@vsphere.local
    password: ba*!T8Gr9Xa7BL7J
  # Provide the name for the persistent disk to be used by the deployment (ending
  # in .vmdk). Any directory in the supplied path must be created before deployment
  dataDisk: "admin-cluster.vmdk"
antiAffinityGroups:
            enabled: false
# (Required) Network configuration
network:
  ipMode:
    # (Required) Define what IP mode to use ("dhcp" or "static")
    type: static
    # # (Required when using "static" mode) The absolute or relative path to the yaml file
    # # to use for static IP allocation
    ipBlockFilePath: "/home/ubuntu/2-gke-onprem-packet/admin-cluster/admin-cluster-ipblock.yaml"
  # (Required) The Kubernetes service CIDR range for the cluster. Must not overlap
  # with the pod CIDR range
  serviceCIDR: 172.31.0.0/16
  # (Required) The Kubernetes pod CIDR range for the cluster. Must not overlap with
  # the service CIDR range
  podCIDR: 172.30.0.0/16
  vCenter:
    # vSphere network name
    networkName: "VM Private Net"
  hostConfig:
    dnsServers:
      - "172.16.3.1"
    ntpServers:
      - "ntp.ubuntu.com"
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "172.16.3.15"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    addonsVIP: "172.16.3.17"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  kind: Seesaw
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   ingressHTTPNodePort: 32527
  #   ingressHTTPSNodePort: 30139
  #   controlPlaneNodePort: 30968
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address: ""
  #   credentials:
  #     username: ""
  #     password: ""
  #   partition: ""
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  seesaw:
    # (Required) The absolute or relative path to the yaml file to use for IP allocation
    # for LB VMs. Must contain one or two IPs.
    ipBlockFilePath: "/home/ubuntu/2-gke-onprem-packet/admin-cluster/admin-cluster-lb-ipblock.yaml"
    # (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
    # be between 1-255 and unique in a VLAN.
    vrid: 4
    # (Required) The IP announced by the master of Seesaw group
    masterIP: "172.16.3.12"
    # (Required) The number CPUs per machine
    cpus: 4
    # (Required) Memory size in MB per machine
    memoryMB: 8192
    # (Optional) Network that the LB interface of Seesaw runs in (default: cluster
    # network)
    vCenter:
      # vSphere network name
      networkName: "VM Private Net"
    # (Optional) Run two LB VMs to achieve high availability (default: false)
    enableHA: false
# (Optional) Specify the proxy configuration
proxy:
  # The URL of the proxy
  url: ""
  # The domains and IP addresses excluded from proxying
  noProxy: ""
# # (Optional) Use a private Docker registry to host GKE images
# privateRegistry:
#   # Do not include the scheme with your registry address
#   address: ""
#   credentials:
#     username: ""
#     password: ""
#   # The absolute or relative path to the CA certificate for this registry
#   caCertPath: ""
# (Required): The absolute or relative path to the GCP service account key for pulling
# GKE images
gcrKeyPath: /home/ubuntu/2-gke-onprem-packet/gcp_keys/whitelisted-key.json
# (Optional) Specify which GCP project to connect your logs and metrics to
stackdriver:
  projectID: aflalo-anthos
  # A GCP region where you would like to store logs and metrics for this cluster.
  clusterLocation: "europe-west1"
  enableVPC: false
  # The absolute or relative path to the key file for a GCP service account used to
  # send logs and metrics from the cluster
  serviceAccountKeyPath: /home/ubuntu/2-gke-onprem-packet/gcp_keys/log-mon-sa-2009181532.json
# # (Optional) Configure kubernetes apiserver audit logging
# cloudAuditLogging:
#   projectid: ""
#   # A GCP region where you would like to store audit logs for this cluster.
#   clusterlocation: ""
#   # The absolute or relative path to the key file for a GCP service account used to
#   # send audit logs from the cluster
#   serviceaccountkeypath: ""
